#!/usr/bin/python3
# me - this DAT
# scriptOp - the OP which is cooking


# called whenever custom pulse parameter is pushed
def onPulse(par):
    return


def onCook(scriptOp):
    # a = numpy.random.randint(0, high=255, size=(2, 2, 4), dtype='uint8')
    # scriptOp.copyNumpyArray(a)

    image_queue = me.parent().fetch('image_queue', None)
    if image_queue is not None:
        try:
            numpy_image = image_queue.get_nowait()
        except:
            numpy_image = None
        if numpy_image is not None:
            scriptOp.copyNumpyArray(numpy_image)

    return


# press 'Setup Parameters' in the OP to call this function to re-create the parameters.
def onSetupParameters(scriptOp):
    """Auto-generated by Component Editor"""
    # manual changes to anything other than parJSON will be	# destroyed by Comp Editor unless doc string above is
    # changed

    TDJSON = op.TDModules.mod.TDJSON
    parJSON = """
    {}
    """
    parData = TDJSON.textToJSON(parJSON)
    TDJSON.addParametersFromJSONOp(scriptOp, parData, destroyOthers=True)
